### ISSUE TITLE
SDK crashes on unexpected URL

### ISSUE THREAD

**Issue by Roconda** [O2MC/dimml-mobile-sdk#3]
When configuring the the end point URL to a random port on localhost the SDK crashes the app completely.

The SDK should never crash the app.

**Comment by Roconda** [comment]
The following error logs have been thrown on Android:

```
06-22 13:16:10.468 4612-4633/? E/DATA: {"eventType":"alias","elementValue":"{\"event\":\"alias\",\"identity\":\"\",\"time\":\"2018-06-22 13:16:05.829\",\"properties\":\"Name\"}","trackingDateTime":"2018-06-22T11:16:10Z"}
06-22 13:16:10.481 4612-4633/? E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: io.o2mc.app, PID: 4612
    java.lang.IllegalArgumentException: unexpected url: http://127.0.0.1:76644/events
        at okhttp3.Request$Builder.url(Request.java:143)
        at io.o2mc.sdk.util.DataPoster.post(DataPoster.java:56)
        at io.o2mc.sdk.Datastreams.DatastreamsDispatcher.dispatch(DatastreamsDispatcher.java:73)
        at io.o2mc.sdk.Tracker$Dispatcher.run(Tracker.java:193)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
```

**Comment by Roconda** [comment]
iOS does not seem to be affected.
